# Generated by Django 3.2.9 on 2021-12-01 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.CharField(default='not provided', max_length=200)),
                ('company_address_city', models.CharField(default='not provided', max_length=200)),
                ('company_address_plz', models.CharField(default='not provided', max_length=200)),
                ('company_address_street', models.CharField(default='not provided', max_length=200)),
                ('company_approved', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Appl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_date', models.DateField(auto_now_add=True)),
                ('appl_ip_addr', models.GenericIPAddressField(unpack_ipv4=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
    ]
