# Generated by Django 3.2.9 on 2021-11-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_approved',
            field=models.BooleanField(default=False),
        ),
    ]
