# Generated by Django 3.2.9 on 2021-11-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_company_company_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_address_city',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='company_address_plz',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='company_address_street',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.CharField(default='not provided', max_length=200),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_firstName', models.CharField(max_length=50)),
                ('contact_lastName', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(default='not provided', max_length=50)),
                ('contact_email', models.CharField(default='not provided', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
    ]
