# Generated by Django 3.2.9 on 2021-11-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_contact_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_date', models.DateField(auto_now_add=True)),
                ('appl_ip_addr', models.GenericIPAddressField(unpack_ipv4=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
    ]
