# Generated by Django 3.2.9 on 2021-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_appl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ManyToManyField(to='jobapp.Company'),
        ),
    ]
