# Generated by Django 3.2.9 on 2021-11-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20211125_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
            preserve_default=False,
        ),
    ]
