# Generated by Django 3.2.9 on 2021-12-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_description', models.CharField(default='not provided', max_length=200)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Employee'), (2, 'Company-Employer')], default=1, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address_city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address_plz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address_street',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Appl',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='jobapp.Tag'),
        ),
    ]
